services:
  crawler:
    build: .
    volumes:
      # Mount progress files directory to persist crawler progress
      - ./crawler_progress:/app/crawler_progress
      - ./proxies.json:/app/proxies.json  # Mount proxies.json
      - ./found_skus:/app/found_skus  # Mount found_skus directory
    environment:
      - PYTHONUNBUFFERED=1  # Enable real-time logging
      - API_URL=http://66.94.112.14:8080
      - EMAIL_SENDER=ddqphuoc@gmail.com
      - EMAIL_PASSWORD=wfbgqfairssewhfk
    # restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # tail: "100"
    ports:
      - "8000:8000"  # Expose the FastAPI port 