services:
  crawler:
    build: .
    volumes:
      # Mount progress files directory to persist crawler progress
      - ./crawler_progress:/app/crawler_progress
      - ./proxies.json:/app/proxies.json  # Mount proxies.json
    environment:
      - PYTHONUNBUFFERED=1  # Enable real-time logging
      - API_URL=http://host.docker.internal:8080/api/products/update
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 