services:
  crawler:
    build: .
    volumes:
      # Mount progress files directory to persist crawler progress
      - ./crawler_progress:/app/crawler_progress
      - ./proxies.json:/app/proxies.json  # Mount proxies.json
      - ./found_skus:/found_skus  # Changed from /app/found_skus to /found_skus
    environment:
      - PYTHONUNBUFFERED=1  # Enable real-time logging
      - API_URL=http://66.94.112.14:8080
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_PREFIX=${S3_PREFIX}
    # restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # tail: "100"
    ports:
      - "8000:8000"  # Expose the FastAPI port 